export const REQUEST_THRESHOLD = 'REQUEST_THRESHOLD';
export const RECEIVE_THRESHOLD = 'RECEIVE_THRESHOLD';
export const SET_CURRENCY = 'SET_CURRENCY';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
